parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: ssm
    database_user: root
    database_password: root
    redis_dsn: 'redis://localhost'
    redis_prefix: 'openrepeater:'